const errors = {
    PRODUCTS_NOT_EXIST: 'No hay productos',
    CART_NOT_EXIST: 'El carrito no existe',
    PRODUCT_TO_ADD_NOT_EXIST: 'El producto que intenta añadir no existe',
    PRODUCT_NOT_EXIST: 'El producto que busca no existe',
    PRODUCT_CODE_EXIST: 'El Producto que intenta añadir tiene un código que ya existe',
    PRODUCT_MUST_HAVE_CODE: 'El producto debe tener un código',
    PRODUCT_MUST_HAVE_PRICE: 'El producto debe tener un precio',
    PRODUCT_MUST_HAVE_STOCK: 'El producto debe tener un stock',
    PRODUCT_MUST_HAVE_POSITIVE_STOCK: 'El stock no puede ser negativo',
    PRODUCT_MUST_HAVE_POSITIVE_PRICE: 'El precio no puede ser negativo',
    PRODUCT_MUST_HAVE_TITLE: 'El producto debe tener un título',
    PRODUCT_MUST_HAVE_DESCRIPTION: 'El producto debe tener una descripción',
    PRODUCT_MUST_HAVE_THUMBNAILS: 'El producto debe tener un thumbnail',
    PRODUCT_MUST_HAVE_CATEGORY: 'El producto debe tener una categoria',
    ERROR_READING_FILE: 'Error al leer el archivo',
    ERROR_WRITING_FILE: 'Error al escribir el archivo',
    ERROR_DELETING_FILE: 'Error al eliminar el archivo',
    ERROR_UPDATING_FILE: 'Error al actualizar el archivo',
    ERROR_CREATING_FILE: 'Error al crear el archivo',
    ERROR_FILE_NOT_EXIST: 'El archivo no existe',
    ERROR_FILE_EXIST: 'El archivo ya existe',
    ERROR_FILE_EMPTY: 'El archivo está vacío',
    ERROR_FILE_NOT_EMPTY: 'El archivo no está vacío',
    ERROR_FILE_NOT_READABLE: 'El archivo no es legible',
    ERROR_FILE_NOT_WRITABLE: 'El archivo no es escribible',
    ERROR_FILE_NOT_DELETABLE: 'El archivo no es eliminable',
    ERROR_FILE_NOT_EXIST_OR_EMPTY: 'El archivo no existe o está vacío',
    ADDING_PRODUCT_TO_CART_ERROR: 'Error al añadir el producto al carrito',
    DELETE_PRODUCT_FROM_CART_ERROR: 'Error al eliminar el producto del carrito',
    GET_CARTS_ERROR: 'Error al obtener los carritos',
    GET_CART_ERROR: 'Error al obtener el carrito',
    GET_PRODUCTS_FROM_CART_ERROR: 'Error al obtener los productos del carrito',
    DELETE_CART_ERROR: 'Error al eliminar el carrito',
    CREATE_CART_ERROR: 'Error al crear el carrito',
    GET_PRODUCTS_ERROR: 'Error al obtener los productos',
    GET_PRODUCT_ERROR: 'Error al obtener el producto',
    DELETE_PRODUCT_ERROR: 'Error al eliminar el producto',
    CREATE_PRODUCT_ERROR: 'Error al crear el producto',
    UPDATE_PRODUCT_ERROR: 'Error al actualizar el producto',
}

export default errors;